# Generated by Django 6.0.3 on 2026-04-05 09:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1976d2', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#dc004e', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(default='#f50057', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#333333', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('font_family', models.CharField(default='Roboto, sans-serif', max_length=100)),
                ('heading_font', models.CharField(default='Poppins, sans-serif', max_length=100)),
                ('border_radius', models.IntegerField(default=8)),
                ('spacing_unit', models.IntegerField(default=8)),
                ('header_style', models.CharField(default='modern', max_length=50)),
                ('footer_style', models.CharField(default='minimal', max_length=50)),
                ('button_style', models.CharField(default='rounded', max_length=50)),
                ('card_shadow', models.CharField(default='0 2px 8px rgba(0,0,0,0.1)', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lebens- und Sozialberatung', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=300)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_site', to='cms_pages.designtemplate')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
