# Generated by Django 6.0.3 on 2026-04-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0002_designtemplate_page_created_at_page_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('layout_type', models.CharField(choices=[('landing', 'Landing Page'), ('about', 'About Page'), ('services', 'Services Page'), ('portfolio', 'Portfolio Page'), ('contact', 'Contact Page'), ('custom', 'Custom Layout')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms_pages.pagelayout'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Section'), ('cards', 'Card Grid'), ('timeline', 'Timeline'), ('gallery', 'Image Gallery'), ('video', 'Video Section'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('text', 'Text Content'), ('team', 'Team Members'), ('pricing', 'Pricing Table'), ('faq', 'FAQ Accordion'), ('contact_form', 'Contact Form')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('background_type', models.CharField(choices=[('none', 'None'), ('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image'), ('pattern', 'Pattern')], default='none', max_length=50)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('padding_top', models.IntegerField(default=80)),
                ('padding_bottom', models.IntegerField(default=80)),
                ('is_full_width', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('custom_css_class', models.CharField(blank=True, max_length=100)),
                ('page_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms_pages.pagelayout')),
            ],
            options={
                'ordering': ['page_layout', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image'), ('video', 'Video'), ('card', 'Card'), ('timeline_item', 'Timeline Item'), ('testimonial', 'Testimonial'), ('team_member', 'Team Member'), ('feature', 'Feature'), ('stat', 'Statistic'), ('button', 'Button'), ('icon', 'Icon')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_target', models.CharField(default='_self', max_length=20)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('icon_color', models.CharField(blank=True, max_length=7)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='cms_pages.section')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
