# Generated by Django 6.0.3 on 2026-04-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0003_pagelayout_page_layout_section_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('header', 'Header'), ('navigation', 'Navigation'), ('footer', 'Footer')], max_length=50)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('logo_alt', models.CharField(blank=True, max_length=200)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('text_color', models.CharField(blank=True, max_length=7)),
                ('show_social_links', models.BooleanField(default=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('custom_html', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 320 characters)', max_length=320),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave blank to use page title)', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type',
            field=models.CharField(default='website', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='robots_meta',
            field=models.CharField(default='index, follow', help_text='Robots meta tag', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data'),
        ),
        migrations.AddField(
            model_name='page',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('is_external', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('global_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='cms_pages.globaltemplate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_pages.navigationitem')),
            ],
            options={
                'ordering': ['global_template', 'order'],
            },
        ),
    ]
