# Generated by Django 6.0.3 on 2026-04-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0004_globaltemplate_page_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltemplate',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Accent color for links and highlights', max_length=7),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_content_layout',
            field=models.ForeignKey(blank=True, help_text='Optional: Use a PageLayout for footer content sections', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_templates', to='cms_pages.pagelayout'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_copyright_text',
            field=models.CharField(blank=True, help_text='Copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_layout',
            field=models.CharField(blank=True, choices=[('single_column', 'Single Column'), ('two_columns', 'Two Columns'), ('three_columns', 'Three Columns'), ('four_columns', 'Four Columns')], help_text='Footer column layout', max_length=50),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_newsletter_text',
            field=models.CharField(blank=True, help_text='Newsletter signup text', max_length=200),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_show_back_to_top',
            field=models.BooleanField(default=True, help_text='Show back to top button'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_show_logo',
            field=models.BooleanField(default=True, help_text='Show logo in footer'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='footer_show_newsletter',
            field=models.BooleanField(default=False, help_text='Show newsletter signup'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_cta_text',
            field=models.CharField(blank=True, help_text='Call-to-action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_cta_url',
            field=models.CharField(blank=True, help_text='Call-to-action button URL', max_length=500),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_dropdown_enabled',
            field=models.BooleanField(default=True, help_text='Enable dropdown menus'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('side', 'Side'), ('bottom', 'Bottom')], help_text='Navigation position (for navigation templates)', max_length=20),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_search_enabled',
            field=models.BooleanField(default=False, help_text='Show search bar in navigation'),
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='nav_sticky',
            field=models.BooleanField(default=False, help_text='Sticky navigation on scroll'),
        ),
    ]
