# Generated by Django 6.0.3 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0005_globaltemplate_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='decade_theme_id',
            field=models.CharField(blank=True, help_text='ID of the selected decade theme (e.g., 90s-1, 2020s-3)', max_length=50, null=True),
        ),
    ]
