# Generated by Django 6.0.3 on 2026-04-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0006_sitesettings_decade_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_blocks', to='cms_pages.page'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='link_type',
            field=models.CharField(choices=[('external', 'External URL'), ('internal', 'Internal Page'), ('none', 'No Link')], default='none', max_length=20),
        ),
    ]
