# Generated by Django 6.0.3 on 2026-04-06 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0007_contentblock_internal_page_contentblock_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecadeTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(help_text='Unique theme ID (e.g., 90s-1, 2000s-2)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('decade', models.CharField(choices=[('90s', '1990s'), ('2000s', '2000s'), ('2010s', '2010s'), ('2020s', '2020s')], max_length=10)),
                ('variation', models.IntegerField(help_text='Theme variation number (1-3)')),
                ('primary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('font_family', models.CharField(max_length=200)),
                ('heading_font', models.CharField(max_length=200)),
                ('border_radius', models.IntegerField(default=8)),
                ('spacing_unit', models.IntegerField(default=8)),
                ('card_shadow', models.CharField(max_length=200)),
                ('button_style', models.CharField(choices=[('pill', 'Pill'), ('squared', 'Squared'), ('soft-rounded', 'Soft Rounded'), ('rounded', 'Rounded')], default='rounded', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for special effects')),
                ('is_predefined', models.BooleanField(default=True, help_text='True for original 12 themes, False for user customizations')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active theme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Decade Theme',
                'verbose_name_plural': 'Decade Themes',
                'ordering': ['decade', 'variation'],
            },
        ),
    ]
