# Generated by Django 6.0.3 on 2026-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0008_decadetheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Section'), ('cards', 'Card Grid'), ('timeline', 'Timeline'), ('gallery', 'Image Gallery'), ('video', 'Video Section'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('text', 'Text Content'), ('team', 'Team Members'), ('pricing', 'Pricing Table'), ('faq', 'FAQ Accordion'), ('contact_form', 'Contact Form'), ('stats', 'Stats/Numbers'), ('logo_grid', 'Logo Grid'), ('process_steps', 'Process Steps'), ('newsletter', 'Newsletter Signup')], max_length=50),
        ),
    ]
