# Generated by Django 6.0.3 on 2026-04-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0009_alter_section_section_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(help_text='Unique subdomain (e.g., max-mustermann)', max_length=63, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain if connected', max_length=255, null=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='starter', max_length=20)),
                ('site_name', models.CharField(default='Lebens- und Sozialberatung', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=300)),
                ('cal_link', models.CharField(blank=True, help_text='Cal.com booking link', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='globaltemplate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_templates', to='cms_pages.site'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cms_pages.site'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='cms_pages.site'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='cms_pages.site'),
        ),
    ]
