# Generated by Django 5.2.13 on 2026-04-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0010_alter_globaltemplate_name_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.PositiveIntegerField(default=0, help_text='Sekunden')),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('top_pages', models.JSONField(default=list, help_text='Top 10 Seiten mit Views')),
                ('referrers', models.JSONField(default=dict, help_text='Traffic-Quellen')),
                ('devices', models.JSONField(default=dict, help_text='Device-Aufteilung')),
                ('countries', models.JSONField(default=dict, help_text='Länder-Verteilung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='cms_pages.site')),
            ],
            options={
                'verbose_name': 'Tagesstatistik',
                'verbose_name_plural': 'Tagesstatistiken',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['site', '-date'], name='cms_pages_d_site_id_622d9e_idx')],
                'unique_together': {('site', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(default='/', max_length=255)),
                ('country', models.CharField(blank=True, help_text='ISO Ländercode', max_length=2)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20)),
                ('browser_family', models.CharField(blank=True, max_length=50)),
                ('os_family', models.CharField(blank=True, max_length=50)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hour', models.IntegerField()),
                ('date', models.DateField(db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='cms_pages.site')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', 'date', '-timestamp'], name='cms_pages_p_site_id_df4f21_idx'), models.Index(fields=['site', 'page_path', 'date'], name='cms_pages_p_site_id_fbe769_idx')],
            },
        ),
    ]
