# Generated by Django 5.2.13 on 2026-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0011_dailystats_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_trashed',
            field=models.BooleanField(default=False, help_text='Moved to trash, pending deletion'),
        ),
        migrations.AddField(
            model_name='page',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
